FROM node:16-alpine3.12 as hosted

# set the working direction
WORKDIR /app

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY . .

RUN npm install

# add app
COPY . ./

# just build an image for hosting
# as nginx will serve the static files from nginx container
RUN npm run build

FROM hosted as production

RUN npm i -g serve

CMD serve build -p ${APP_FRONTEND_PORT}
