FROM node:16-alpine3.12 as production

# set the working direction
WORKDIR /app

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY . .

RUN npm install

# add app
COPY . ./

RUN npm run build
