version: '3.8'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile.hosted
  backend:
    image: backend:hosted
    container_name: backend-hosted
    build:
      target: production
      dockerfile: ./Dockerfile.prod
  frontend:
    image: frontend:hosted
    container_name: frontend-hosted
    build:
      args:
        - REACT_APP_API_HOST=https://app.flowser.dev
      target: hosted
      dockerfile: ./Dockerfile.prod
    volumes:
      - frontend-volume:/app
    restart: "no"
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./server/nginx:/etc/nginx/conf.d
      - ./server/certbot/conf:/etc/letsencrypt
      - ./server/certbot/www:/var/www/certbot
      - frontend-volume:/var/www/frontend
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - flowser-network
  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./server/certbot/conf:/etc/letsencrypt
      - ./server/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - flowser-network

volumes:
  frontend-volume:
