export const routes = {
  start: "/projects",
  configure: "/projects/configure",
  configureExisting: "/projects/configure/:id",
  configureCurrent: "/configure/:id",
  accounts: "/accounts",
  blocks: "/blocks",
  transactions: "/transactions",
  contracts: "/contracts",
  events: "/events",
  interactions: "/interactions",
  logs: "/logs",
  firstRouteAfterStart: "/accounts",
  project: "/project",
};
