export enum FlowserIpcEvent {
  APP_DIRECTORY_PICKER_SHOW = 'APP_DIRECTORY_PICKER_SHOW',
  APP_UPDATE_START = 'APP_UPDATE_START',
  APP_UPDATE_PROGRESS = 'APP_UPDATE_PROGRESS',
  APP_UPDATE_END = 'APP_UPDATE_END',
  APP_EXIT = 'APP_EXIT',
  APP_LOG = 'APP_LOG',
  APP_DEPENDENCY_ERRORS_LIST = 'APP_DEPENDENCY_ERRORS_LIST',

  WORKSPACES_CLOSE = 'WORKSPACES_CLOSE',
  WORKSPACES_OPEN = 'WORKSPACES_OPEN',
  WORKSPACES_CREATE = 'WORKSPACES_CREATE',
  WORKSPACES_UPDATE = 'WORKSPACES_UPDATE',
  WORKSPACES_LIST = 'WORKSPACES_LIST',
  WORKSPACES_FIND_BY_ID = 'WORKSPACES_FIND_BY_ID',
  WORKSPACES_REMOVE = 'WORKSPACES_REMOVE',
  WORKSPACES_DEFAULT_SETTINGS = 'WORKSPACES_DEFAULT_SETTINGS',

  INDEX_GET_ALL = 'INDEX_GET_ALL',

  INTERACTIONS_PARSE = 'INTERACTIONS_PARSE',
  INTERACTIONS_LIST_TEMPLATES = 'INTERACTIONS_LIST_TEMPLATES',

  FLOW_CLI_GET_INFO = 'FLOW_CLI_GET_INFO',

  FLOW_CONFIG_GET_CONTRACTS = 'FLOW_CONFIG_GET_CONTRACTS',
  FLOW_CONFIG_GET_ACCOUNTS = 'FLOW_CONFIG_GET_ACCOUNTS',

  FLOW_TRANSACTION_SEND = 'FLOW_TRANSACTION_SEND',
  FLOW_SCRIPT_EXECUTE = 'FLOW_SCRIPT_EXECUTE',
  FLOW_ACCOUNT_GET_INDEX = 'FLOW_ACCOUNT_GET_INDEX',

  WALLET_ACCOUNT_CREATE = 'WALLET_ACCOUNT_CREATE',
  WALLET_KEY_LIST = 'WALLET_KEY_LIST',

  SNAPSHOTS_ROLLBACK_TO_HEIGHT = 'SNAPSHOTS_ROLLBACK_TO_HEIGHT',
  SNAPSHOTS_JUMP_TO = 'SNAPSHOTS_JUMP_TO',
  SNAPSHOTS_LIST = 'SNAPSHOTS_LIST',
  SNAPSHOTS_CREATE = 'SNAPSHOTS_CREATE',

  PROCESS_LOGS_LIST = 'PROCESS_LOGS_LIST',
}
